[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
octasol_contract = "tMf5EmV2h6sMJ2QMFU6766ACJpf7NTuamPzCudaNFus"


[programs.devnet]
octasol_contract ="Ay8FsRFjAN9KmD9S6USMuzS7wnobxqFqwBiQGGiYqen5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
